language: scala
jdk: oraclejdk8
scala:
  - 2.11.12
  - 2.12.6
  - 2.13.0-M4
matrix:
  include:
  - scala: 2.12.6
    jdk: oraclejdk10
  - scala: 2.13.0-M5
    script:
    - sbt
      "++${TRAVIS_SCALA_VERSION}!"
      json4s-examples/compile
      json4s-xml/compile
      json4s-scalaz/compile
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers
before_install:
  - export TZ=Australia/Canberra
script:
  - travis_retry sbt "++${TRAVIS_SCALA_VERSION}!" test
before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
